
language: c

sudo: required
services:
  - docker

before_install:
  - grep '\(MemTotal\|SwapTotal\)' /proc/meminfo
  - git show | head -1  # (for matching against commit hash given on the travis log web page)
  - docker pull lambdacube3d/lambdacube3d

script:
  - docker run --rm -it -v `pwd`:/root/source/lambdacube-compiler lambdacube3d/lambdacube3d
    /bin/sh -c "cd /root/source/lambdacube-compiler;./run-test-suite.sh --coverage"
