
language: c

sudo: required
services:
  - docker

matrix:
  fast_finish: true
  include:
    - c: gcc
      env: BUILD_TYPE=build
    - c: clang
      env: BUILD_TYPE=profile
  allow_failures:
    - c: clang

before_install:
  - grep '\(MemTotal\|SwapTotal\)' /proc/meminfo
  - git show | head -1  # (for matching against commit hash given on the travis log web page)
  - docker pull lambdacube3d/lambdacube3d
  - docker run --rm -it -v `pwd`:/root/source/lambdacube-compiler lambdacube3d/lambdacube3d /bin/sh -c "ghc-pkg list"

script:
  - docker run --rm -it -v `pwd`:/root/source/lambdacube-compiler lambdacube3d/lambdacube3d /bin/sh -c "/root/source/lambdacube-compiler/travis/travis-${BUILD_TYPE}.sh"
