resolver: lts-10.4
packages:
- '.'
- location:
    git: https://github.com/lambdacube3d/lambdacube-ir.git
    commit: b8b4ec9fa985b2eb756ac1a5a65af483a0bd586b
  subdirs:
    - lambdacube-ir.haskell
  extra-dep: true
extra-deps:
- vect-0.4.7
- megaparsec-6.4.0
- parser-combinators-0.4.0
flags:
  lambdacube-compiler:
    alltest: true
extra-package-dbs: []
